### ISSUE TITLE
Saving generated meshes

### ISSUE THREAD

**Issue by akomarichev** [SevenLJY/cage#1]
Hi,

Thank you for your great work! I am curious how to save generated objects as meshes / urdf in your pipeline once the model is fully trained?

**Comment by SevenLJY** [comment]
Hi @akomarichev, thanks for your interest in our work, and sorry for the late reply..
We used a simple retrieval strategy to obtain the meshes for each part. The code can be found in the `retrieval` folder.
A "pseudo" usage example is as below.
```
# hashbook is under the same folder
obj_candidates = find_obj_candidates(json_data, gt_data_dir, hashbook_path)    
parts_to_render = pick_and_rescale_parts(json_data, obj_candidates, gt_data_dir)
```
