### ISSUE TITLE
Lack of OODPredDataset in datamodules.datasets

### ISSUE THREAD

**Issue by YexiongLin** [SevenLJY/cage#2]
Hi, I found this code lacks a module (OODPredDataset) in datamodules.datasets.

``
ImportError: cannot import name 'OODPredDataset' from 'datamodules.datasets'
``

**Comment by SevenLJY** [comment]
Hi @YexiongLin! Thanks for your interest in our work and for pointing this out. 
We will update our codebase and fix this issue soon while preparing for the camera-ready version.

**Comment by zcczhang** [comment]
I just wonder if there's any estimated time for this fix? Thank you!

**Comment by SevenLJY** [comment]
`OODPredDataset` has been added to the code base. Thanks for your patience.
