### ISSUE TITLE
Preprocessing for PartNet-Mobility dataset

### ISSUE THREAD

**Issue by Wentap123** [SevenLJY/cage#6]
Hello! Thanks for the wonderful work and for sharing the pretrained weights and preprocessed data. if you could share the preprocessing scripts or code you used in your project.
Thanks in advance!

**Comment by SevenLJY** [comment]
Hi @Vinter8848.

Thanks for your interest in our work. We have updated the preprocessing script in `preprocess.py`. Please check it out!

Sorry for the late reply and thanks for your patience.

Hope it helps!

Jiayi

**Comment by Wentap123** [comment]
Thanks for the updated preprocessing script! This really helps me a lot ! ! !
